### ISSUE TITLE
Read from credentials files

### ISSUE THREAD

**Issue by fernandascovino** [JoaoCarabetta/project-templates#22]
Make a `.yml ` file with all the inputs called by bash - and you'll never need to enter them again

**Comment by JoaoCarabetta** [comment]
Can you explain the idea? I didnt get it

**Comment by fernandascovino** [comment]
These entries we use (username, password, name) could be all in a file read from `start_project.sh`, like:

```yaml
my_cred:
    name: eu
    password: panquecas
    username: euzinha

```

so that you don't need to fill them all the time... and maybe you could only pass the key (makes it easy if u also want to use multiple accounts)
